/*
 * Copyright 2018 Albert Santos.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package lbjgnash.ui.reportview;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * This manages the report column data for a specific date (which was generated by
 * the report's date generator.
 */
public class DateEntry implements Comparable<DateEntry> {

    final LocalDate startDate;
    final LocalDate endDate;
    final int index;
    final List<ColumnEntry> columnEntries = new ArrayList<>();

    public DateEntry(LocalDate dateStart, LocalDate dateEnd, int index) {
        this.startDate = dateStart;
        this.endDate = dateEnd;
        this.index = index;
    }

    public ColumnEntry getColumnEntryAtIndex(int index) {
        while (index >= columnEntries.size()) {
            columnEntries.add(new ColumnEntry());
        }
        return columnEntries.get(index);
    }

    @Override
    public int compareTo(DateEntry o) {
        return endDate.compareTo(o.endDate);
    }
    
}
